### ISSUE TITLE
No phoenix dependency

### ISSUE THREAD

**Issue by sleipnir** [E-xyza/Apical#17]
Hi. Nice library.

I would really like to be able to use something like what this library provides without the direct need for Phoenix.
Some services are too simple for Phoenix features and could depend only on Plug, without direct dependency on Phoenix.

**Comment by ityonemo** [comment]
this is planned!, but not till 0.3

**Comment by sleipnir** [comment]
> this is planned!, but not till 0.3

Cool. Thanks

**Comment by ityonemo** [comment]
Thanks for keeping it on the issue list.  I *might* try to do it in 0.2 to make sure my abstractions are correct before getting too far into features.

**Comment by sleipnir** [comment]
> Thanks for keeping it on the issue list. I _might_ try to do it in 0.2 to make sure my abstractions are correct before getting too far into features.

Cool. Great work. This will be very helpful for me. I will try to help however I can.

**Comment by ityonemo** [comment]
so the complexity is going to be because it's rather tricky in base Plug to support plug pipelines on a path parameter basis.  I think I know one way to do it, (create a module plug per operationId) but I would like to see how phoenix does it first.

**Comment by ityonemo** [comment]
Basics done here:  [1b2087a](https://github.com/E-xyza/Apical/pull/44/commits/1b2087a14844ad366003f7ad7066c8b55a23468b), needs some tests on path parameter resolution.

**Comment by ityonemo** [comment]
will close when:
- [ ] path parameter resolution test is verified
- [ ] feature is documented

**Comment by sleipnir** [comment]
Great work here @ityonemo
